name: backup_restore_books
description: A HiveDB sample project that demonstrates backup & restore functionality.

publish_to: "none"

version: 1.0.0

environment:
  sdk: '>=2.12.0'

dependencies:
  flutter:
    sdk: flutter
  hive: any
  hive_flutter: any
  path_provider: ^2.0.0
  file_picker: ^4.6.0

  cupertino_icons: ^1.0.0

flutter:
  uses-material-design: true
dev_dependencies:
  flutter_test:
    sdk: flutter
