name: contacts
description: A HiveDB sample project that demonstrates TypeAdapter functionality.

version: 1.0.0+1

environment:
  sdk: '>=2.12.0'

dependencies:
  flutter:
    sdk: flutter
  hive: any
  hive_flutter: any

dev_dependencies:
  hive_generator: any
  build_runner: ^2.1.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
